apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: platform-sdk
  title: Platform SDK
  description: >
    Provider-abstracted Python SDK for all platform concerns —
    identity, logging, inference, vector search, auth, data, metrics, and more.
    Two-surface architecture: agent surface for AI agents, service surface for backend services.
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - python
    - sdk
    - platform
    - genai
spec:
  type: library
  owner: platform-team
  lifecycle: production
  system: dopejarmo
